let INITIAL_CURRENT = 40;

const SLIDES = [
  ["🪲🐞🐜🐝🦟"],
  ['"foo" == "foo"'],
  ["10 == 10"],
  ["{} === {}"],
  ["[] == []"],
  ["[] == ![]"],
  ["0 / 0"],
  ['+"💀"'],
  ["typeof NaN"],
  ["NaN === NaN"],
  ["false == 0"],
  ['false == "0"'],
  ['0 == "0"'],
  ['[] == ""'],
  ['0 == ""'],
  ["null == undefined"],
  ["null === undefined"],
  ["0.1 + 0.2"],
  ["'5' + 3"],
  ["'5' - 3"],
  ["{} + []", "0"],
  ["[] + {}"],
  ['+"75"'],
  ["+[]"],
  ["+!![]"],
  ["+{}"],
  ["true + true + true"],
  ["String(75)"],
  ['Number("75")'],
  ["Number([])"],
  ["Number([99])"],
  ["Number([1,2])"],
  ["Boolean([])"],
  ["Boolean({})"],
  ['Boolean("")'],
  ['"😎" > "😀"'],
  ['"🍏" > "🍎"'],
  ['"🍕".toUpperCase()'],
  ['"4️⃣".length'],
  ['"🔢".length'],
  ['"🍏🍏".replace("🍏","🍎")'],
  ["I ❤️ JavaScript"]
];