let INITIAL_CURRENT = 0;

const SLIDES = [
  ['"I ❤️ JavaScript"', "🔎 🪲🐞🐜🐝🦟"],
  ['"foo" == "foo"'],
  ["10 == 10"],
  ["{} === {}"],
  ["[] == []"],
  ["[] == ![]"],
  ["0 / 0"],
  ['+"💀"'],
  ["typeof NaN"],
  ["NaN === NaN"],
  ["false == 0"],
  ['false == "0"'],
  ['0 == "0"'],
  ['[] == ""'],
  ['0 == ""'],
  ["null == undefined"],
  ["null === undefined"],
  ["0.1 + 0.2"],
  ['"5" + 3'],
  ['"5" - 3'],
  ["Math.min() < Math.max()", false, 50],
  ["{} + []", "0"],
  ["[] + {}"],
  ["null + 1"],
  ["null * 5"],
  ['+"75"'],
  ["+[]"],
  ["+!![]"],
  ["+{}"],
  ["true + true + true"],
  ["String(75)"],
  ['Number("75")'],
  ["Number([])"],
  ["Number([99])"],
  ["Number([1,2])"],
  ["Boolean([])"],
  ["Boolean({})"],
  ['Boolean("")'],
  ['"😎" > "😀"'],
  ['"🍏" > "🍎"'],
  ['"🍕".toUpperCase()'],
  ['"🌮🌯🍔".includes("🍕")', false, 60],
  ['"4️⃣".length'],
  ['"🔢".length'],
  ["String.fromCodePoint(0x1f4a9)", false, 50],
  ['"💩💩💩".replace("💩","✅")', false, 50],
  ["I ❤️ JavaScript"]
];